name: macOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and_test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build and test for macOS arm64
        run: |
          xcodebuild clean build test \
            -project EssentialFeed/EssentialFeed.xcodeproj \
            -scheme "CI" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
