name: CI-iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and_test:
    runs-on: macos-latest
    timeout-minutes: 8
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build and test for iOS
        run: |
          xcodebuild clean build test \
            -project EssentialFeed/EssentialFeed.xcodeproj \
            -scheme "CI_iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
